import { Tag, Category, AppSettings, UserStats, SysadminQuest } from './types';

export const DEFAULT_TAGS: Tag[] = [
  { id: 'tag-prod', nameEn: 'Production', nameFa: 'عملیاتی / پروداکشن', color: '#ff4b72', textColor: '#ffffff' }, // Rose
  { id: 'tag-db', nameEn: 'Database', nameFa: 'پایگاه داده', color: '#00f0ff', textColor: '#0e1525' }, // Neon Cyan
  { id: 'tag-backup', nameEn: 'Backup', nameFa: 'پشتیبان / بکاپ', color: '#3b82f6', textColor: '#ffffff' }, // Azure
  { id: 'tag-dev', nameEn: 'Development', nameFa: 'تست و توسعه', color: '#eab308', textColor: '#000000' }, // Gold
  { id: 'tag-tunnel', nameEn: 'Tunnel / VPN', nameFa: 'تونل و فیلترشکن', color: '#a855f7', textColor: '#ffffff' }, // Amethyst
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'cat-personal', nameEn: 'Personal', nameFa: 'شخصی', icon: 'User' },
  { id: 'cat-work', nameEn: 'Corporate Business', nameFa: 'شرکتی و کاری', icon: 'Briefcase' },
  { id: 'cat-freelance', nameEn: 'Freelance Hub', nameFa: 'پروژه‌های فریلنسری', icon: 'Layers' },
];

export const INITIAL_SETTINGS: AppSettings = {
  lang: 'fa',
  theme: 'frosted-glass',
  visibleFields: {
    ip: true,
    sshPort: true,
    credentials: true,
    daysRemaining: true,
    daysCost: true,
    tags: true,
    category: true,
    provider: true,
  },
  security: {
    lockMethod: 'none',
    isLocked: false,
    lockTimeoutMinutes: 10,
  }
};

export const INITIAL_STATS: UserStats = {
  sysadminLevel: 1,
  xp: 0,
  completedQuests: [],
  totalServersCreated: 0,
  totalRenewalsLogged: 0,
};

export const SYSADMIN_TITLES = [
  { level: 1, en: 'Junior Cable Plugger', fa: 'کابل‌پلاگر تازه‌کار (سطح ۱)' },
  { level: 2, en: 'Localhost Dweller', fa: 'ساکن لوکال‌هاست (سطح ۲)' },
  { level: 3, en: 'Sudo Initiate', fa: 'راه‌یافته به تالار سودو (سطح ۳)' },
  { level: 4, en: 'Port Ranger', fa: 'نگهبان پورت‌ها (سطح ۴)' },
  { level: 5, en: 'Docker Tamer', fa: 'رام‌کننده داکر (سطح ۵)' },
  { level: 6, en: 'DNS Warden', fa: 'امیر بخش دی‌ان‌اس (سطح ۶)' },
  { level: 7, en: 'Bandwidth Monarch', fa: 'پادشاه پهنای باند (سطح ۷)' },
  { level: 8, en: 'Kernel Whispering Shaman', fa: 'شامان و مرشد کرنل (سطح ۸)' },
  { level: 9, en: 'Absolute Cloud Overlord', fa: 'فرمانروای مطلق ابرها (سطح ۹)' },
];

export const DEFAULT_QUESTS: SysadminQuest[] = [
  {
    id: 'quest-add-server',
    titleEn: 'Register First Node',
    titleFa: 'ثبت اولین گره سرور',
    descriptionEn: 'Formally index your first operational server in the databank.',
    descriptionFa: 'اولین سرور فعال خود را در بانک اطلاعاتی برنامه ثبت کنید.',
    xpReward: 40,
    completed: false,
  },
  {
    id: 'quest-backup',
    titleEn: 'Secure Safehouse Vault',
    titleFa: 'عملیات قلعه امن (بکاپ)',
    descriptionEn: 'Export a JSON configuration backup to secure your servers info offline.',
    descriptionFa: 'یک نسخه پشتیبان متنی JSON از سرورها برای امنیت آفلاین دانلود کنید.',
    xpReward: 35,
    completed: false,
  },
  {
    id: 'quest-ping',
    titleEn: 'Echo Transmission Pulse',
    titleFa: 'پالس اکو / اکسیژن‌سنج سرور',
    descriptionEn: 'Execute a network diagnostic terminal check (Ping Probe) on any of your nodes.',
    descriptionFa: 'یک آزمایش بررسی اتصال شبکه‌ای (Ping) روی یکی از سرورها در شبیه‌ساز بزنید.',
    xpReward: 25,
    completed: false,
  },
  {
    id: 'quest-renew',
    titleEn: 'Immortalize Server Lease',
    titleFa: 'تمدید اجاره و حیات نود',
    descriptionEn: 'Log a renewal transaction event for any server in your list.',
    descriptionFa: 'یک تراکنش تمدید اجاره برای حفظ بقای یکی از سرورها ثبت کنید.',
    xpReward: 50,
    completed: false,
  },
  {
    id: 'quest-hourly',
    titleEn: 'Provider Fuel Influx',
    titleFa: 'سوخت‌رسانی به تمدید ساعتی',
    descriptionEn: 'Add an hourly hosting account with cloud balance tracking.',
    descriptionFa: 'یک حساب کاربری ارائه‌دهنده با قابلیت تمدید ساعتی و موجودی دلاری ایجاد کنید.',
    xpReward: 45,
    completed: false,
  }
];

export const TRANSLATIONS = {
  en: {
    appTitle: 'JeyNodePad',
    appSubtitle: 'Supreme Sysadmin Hub & Server Vault',
    welcome: 'Welcome to JeyNodePad',
    welcomeDesc: 'Manage and keep track of unlimited servers, calculate renewal timelines, and secure your credentials inside a gamified desktop terminal.',
    langSelect: 'Choose Language / انتخاب زبان',
    themeSelect: 'Choose Initial UI Skin / انتخاب تم برنامه',
    getStarted: 'Onboard & Initialize Terminus',
    dashboard: 'Terminus Node Chamber',
    addServer: 'Deploy New Node',
    serverList: 'Network Node Registries',
    serversCount: 'Servers Indexed',
    trash: 'Ejected Nodes (Trash)',
    providers: 'Hosting Providers',
    settings: 'App Settings',
    backups: 'Backup / Restore',
    stats: 'Sysadmin Rank & Achievements',
    lockApp: 'Vault Screen Lock',
    aboutDev: 'Intelligence Officer Info',
    searchPlaceholder: 'Search by IP, Host, Username or Tag...',
    allCategories: 'All Clusters',
    noServers: 'No servers deployed yet. Click "Deploy New Node" above to populate the nexus.',
    noTrash: 'Recycle bin is empty. Delete undesired nodes to catalog them here.',
    restore: 'Restore',
    permanentDelete: 'Purge Permanently',
    delete: 'Trash Node',
    edit: 'Modify Specs',
    copySuccess: 'Copiable payload transferred to clipboard!',
    daysRemaining: 'Days Remaining',
    daysCost: 'Cost Rate',
    category: 'Network Cluster',
    provider: 'Provider Panel',
    hourly: 'Hourly Billing (Auto-Fuel Indicator)',
    cycleDays: 'Billing Duration (Days)',
    costLabel: 'Maintenance Fee',
    save: 'Confirm Settings',
    cancel: 'Cancel',
    ip: 'IP Address / IP Domain',
    sshPort: 'SSH Network Port',
    username: 'Root Credentials - User',
    password: 'Root Credentials - Password',
    name: 'Server Hostname Accent Name',
    notes: 'Internal Node Operational Directives (Notes)',
    tags: 'Interactive Tags Tagging',
    filterByTag: 'Filter Tag Scope:',
    manageTags: 'Custom Node Tags Control',
    addNewTag: 'Forge Tailored Tag',
    addProvider: 'Register Provider Balance',
    providerName: 'Provider Identity (e.g. Hetzner, LightNode)',
    balance: 'Pre-funded Cash Balance',
    hourlyRateSum: 'Combined Fuel Consumption',
    level: 'Imperial Sysadmin Rank',
    xpNext: 'XP Needed to Climb Ranks',
    quests: 'Guild Quests & Routine Diagnostics',
    completed: 'Mission Accomplished',
    lockTitle: 'Terminal Secured',
    lockSecureDesc: 'Input authorization sequence to de-crypt data vault',
    aboutDesc: 'Engineered as a lightweight, fully self-contained reactive terminal to bypass central surveillance and track personal network arrays without external clouds.',
    creatorName: 'Seyyed Javad Dehnavi',
    creatorTg: 'Join Telegram Dispatch Hub:',
    programVersion: 'Build Release Version',
    exportBackup: 'Export Secure Backup JSON',
    importBackup: 'Import Safe Backup JSON',
    loadFailure: 'Cryptographic payload invalid or files corrupt.',
    importSuccess: 'State synchronized successfully!',
    emptyWarn: 'Please complete all requested protocols before proceding.',
    authMethod: 'Security Locker Mechanism',
    passcodeLabel: 'Set 4-Digit Numeric Passcode',
    passcodePinError: 'PIN incorrect! Transmission access denied.',
    currency: 'Monetary System Unit',
    usd: 'USD ($)',
    eur: 'EUR (€)',
    toman: 'Toman (تومان)',
    hourlyDesc: 'Calculate hourly hosting consumption using Provider Account balance.',
    renewalLogs: 'Historical Leases Renewal logs',
    addRenewalLog: 'Log Node Renewal Payment',
    amountPaid: 'Payment Amount Paid',
    billingRenewedDay: 'Extension Period (Days)',
    noRenewals: 'No lease extensions cataloged for this server cluster.',
    simulateTerminal: 'Interactive SSH & Network Diagnostics simulator',
    terminalPrompt: 'jeynodepad@sysadmin:~$',
    runDiagnostics: 'Launch Ping Probe Diagnostic',
    showDetails: 'Deconstruct Component details',
    hideDetails: 'Collapse Registry',
    levelTitle: 'Sysadmin Rank XP',
    unlockTitle: 'Theme unlocked!',
    copied: 'Copied!',
    visibleFieldsConfig: 'Toggle Visible Columns in registries:',
    saveConfig: 'Consolidate Configurations',
    fuelIndicator: 'Fuel Timeline Indicator',
    daysOfFuel: 'Days of Provider fuel remaining',
    infiniteFuel: 'Unlimited fuel (No hourly servers running)',
    addServerHeading: 'Deploy New Node Registry',
    editServerHeading: 'Upgrade Server Core Node Specs',
    providerBalance: 'Cash Reserve / balance',
    allTags: 'All Tags',
    hourlyBilling: 'Hourly Billing (Provider Balance deduction)',
    monthlyBilling: 'Cycles Duration Billing',
    lastRenewalDate: 'Billing Genesis Date / Base Date',
    addTagBtn: 'Forge Tag',
    addProviderBtn: 'Register Provider Account',
    pingerSim: 'Simulating ping transmission to destination target...',
    pingerOffline: 'Destination unresponsive! (Simulating host port offline)',
    pingerOnline: 'Pulse check returned: 64 bytes from {ip}: icmp_seq=1 ttl=54 time={ms}ms',
    sshCmdCopy: 'Click to copy instant SSH command:',
    pingCmdCopy: 'Click to copy instant Windows CMD ping loop:',
    pinPrompt: 'Enter 4-Digit Security Code:',
    createPinPrompt: 'Create a 4-Digit Entry PIN:',
    confirmPinLock: 'Apply Cryptographic Shield',
    disableLock: 'Strip Cryptographic Lock to open access',
    hourlyBalanceExhaust: 'Account depletion estimated in {days} Days!',
    quickCreds: 'Credentials quick-view & clipboard copier',
    unassigned: 'Unclustered',
    daysLeftText: '{days} days remaining',
    expiredText: 'LEASE EXPIRED ({days} days ago)',
    todayRenew: 'Due Today / Base Date reached!',
    sysadminLog: 'Node Operations Journal',
    viewAllLogs: 'Browse Historical Chronology',
    addLogsTitle: 'Add Entry Protocol Logs',
    deletePermConfirm: 'Are you sure you want to permanently delete this node register? This action is irreversible.',
    untrashConfirm: 'Restore this node to the active cluster list?',
    statsLevel: 'Imperial Rank Level: {level}',
    statsTitleText: 'Sysadmin Code Name: {title}',
    gamificationSubTitle: 'Combat Operations Checklist',
    personalNotesPlaceholder: 'Internal instructions, docker-compose syntax, configuration files, SSH keys, customized internal routing tables...',
    optional: 'Optional',
    searchCategory: 'Filter by Category',
    resetApp: 'Full App Reset',
    resetAppDesc: 'Deletes all servers, configurations, security PIN, databases, and custom settings permanently and returns you to the Welcome board.',
    resetAppConfirm: 'WARNING: This is completely irreversible and will destroy all stored servers, credentials, custom tags, hosting providers, and access codes. Are you absolutely sure you want to delete everything?',
    resetAppBtn: 'Reset Everything Permanently',
    showTrashServers: 'View Deleted Servers (Trash)',
  },
  fa: {
    appTitle: 'JeyNodePad - مدیریت سرورها',
    appSubtitle: 'ثبت اطلاعات، یادداشت‌ها و محاسبه زمان تمدید کلود و سرورها',
    welcome: 'به جِی‌نودپد خوش آمدید',
    welcomeDesc: 'سرورها و اطلاعات اتصال خود را به ساده‌ترین شکل، به صورت کاملاً امن، آفلاین و محلی مدیریت و دوره‌های فاکتور آن‌ها را محاسبه کنید.',
    langSelect: 'انتخاب زبان برنامه',
    themeSelect: 'پوسته و تم گرافیکی برنامه',
    getStarted: 'ورود به برنامه',
    dashboard: 'لیست سرورها',
    addServer: 'افزودن سرور جدید',
    serverList: 'مشخصات سرورها',
    serversCount: 'تعداد کل سرورها',
    trash: 'سرورهای حذف شده',
    providers: 'ارائه‌دهندگان سرویس',
    settings: 'تنظیمات برنامه',
    backups: 'پشتیبان‌گیری و بازیابی داده‌ها',
    stats: 'آمار و اطلاعات',
    lockApp: 'قفل امنیتی ورود',
    aboutDev: 'درباره سازنده',
    searchPlaceholder: 'جستجو در آدرس IP، نام سرور، نام کاربری یا برچسب‌ها...',
    allCategories: 'همه دسته‌بندی‌ها',
    noServers: 'هنوز هیچ سروری ثبت نکرده‌اید. برای شروع دکمه «افزودن سرور جدید» را بالا کلیک کنید.',
    noTrash: 'سطل زباله خالی است.',
    restore: 'بازیابی سرور',
    permanentDelete: 'حذف دائمی سرور',
    delete: 'حذف سرور',
    edit: 'ویرایش مشخصات',
    copySuccess: 'در حافظه کپی شد!',
    daysRemaining: 'روزهای باقی‌مانده از تمدید',
    daysCost: 'هزینه دوره',
    category: 'دسته‌بندی سرور',
    provider: 'ارائه‌دهنده سرویس',
    hourly: 'شارژ و مصرف ساعتی',
    cycleDays: 'زمان انقضا (روز)',
    costLabel: 'هزینه دوره',
    save: 'ذخیره مشخصات سرور',
    cancel: 'انصراف',
    ip: 'آدرس آی‌پی (IP) یا دامنه',
    sshPort: 'پورت SSH',
    username: 'نام کاربری (Username)',
    password: 'رمز عبور (Password)',
    name: 'نام نمایشی یا برچسب سرور (Label)',
    notes: 'یادداشت‌ها و توضیحات مرتبط با سرور',
    tags: 'تگ‌ها (برچسب‌ها)',
    filterByTag: 'فیلتر بر اساس تگ:',
    manageTags: 'مدیریت تگ‌های سرور',
    addNewTag: 'ایجاد تگ رنگی جدید',
    addProvider: 'ثبت ارائه‌دهنده جدید سرور',
    providerName: 'نام ارائه‌دهنده (مانند Hetzner یا DigitalOcean)',
    balance: 'موجودی پیش‌پرداخت',
    hourlyRateSum: 'مجموع مصرف ساعتی سرورهای متصل',
    level: 'سطح کاربری ادمین',
    xpNext: 'تجربه موردنیاز تا سطح بعدی',
    quests: 'وظایف روزانه ادمین',
    completed: 'انجام شد',
    lockTitle: 'برنامه قفل شده است',
    lockSecureDesc: 'رمز عبور خود را وارد کنید تا قفل باز شود',
    aboutDesc: 'یک جعبه ابزار کاملا امن و آفلاین جهت مدیریت، ثبت مشخصات، تاریخ تمدید و موجودی پنل‌های هاستینگ شما بدون نیاز به ارتباط ابری یا سرور خارجی.',
    creatorName: 'سید جواد دهنوی',
    creatorTg: 'کانال ارتباطی و اطلاع‌رسانی تلگرام:',
    programVersion: 'نسخه برنامه',
    exportBackup: 'دانلود فایل پشتیبان (بکاپ JSON)',
    importBackup: 'بارگذاری و بازیابی فایل پشتیبان (بکاپ JSON)',
    loadFailure: 'داده‌های وارد شده معتبر نیستند، لطفا فرمت فایل را بررسی کنید.',
    importSuccess: 'اطلاعات با موفقیت بازیابی و بازگردانی شدند!',
    emptyWarn: 'لطفاً تمام فیلدهای اصلی و الزامی را پر کنید.',
    authMethod: 'رمز ورود ۴ رقمی به برنامه',
    passcodeLabel: 'تعیین رمز ورود عددی ۴ رقمی',
    passcodePinError: 'رمز عبور اشتباه است!',
    currency: 'واحد پولی برنامه',
    usd: 'دلار آمریکا (USD)',
    eur: 'یورو اروپا (EUR)',
    toman: 'تومان ایران (تومان)',
    hourlyDesc: 'محاسبه بقیه زمان روشن ماندن سرورها بر اساس موجودی کل شما در پنل ارائه‌دهنده.',
    renewalLogs: 'تاریخچه تمدیدها و تراکنش‌های این سرور',
    addRenewalLog: 'ثبت پرداخت تمدید سرور',
    amountPaid: 'مبلغ پرداختی فاکتور تمدید',
    billingRenewedDay: 'مدت تمدید مجدد به روز (مثلا ۳۰)',
    noRenewals: 'هیچ سابقه‌ای برای این سرور یافت نشد.',
    simulateTerminal: 'تست اتصال کلاینت و شبیه‌ساز پینگ سرور',
    terminalPrompt: 'jeynodepad@sysadmin:~$',
    runDiagnostics: 'اجرای تست پینگ',
    showDetails: 'مشاهده مشخصات و جزئیات سرور',
    hideDetails: 'بستن جزئیات سرور',
    levelTitle: 'سطح تجربه ادمین',
    unlockTitle: 'تم با موفقیت تغییر یافت!',
    copied: 'در حافظه کپی شد!',
    visibleFieldsConfig: 'فیلتر فیلدهای قابل نمایش در سرورها:',
    saveConfig: 'ذخیره تنظیمات فیلترها',
    fuelIndicator: 'میزان زمان باقی‌مانده از اعتبار پنل',
    daysOfFuel: 'روز حیات باقی‌مانده تا اتمام شارژ پنل',
    infiniteFuel: 'اعتبار بدون دغدغه (هیچ سرور ساعتی متصل نیست)',
    addServerHeading: 'افزودن اطلاعات سرور جدید به برنامه',
    editServerHeading: 'ویرایش اطلاعات و متادیتای سرور',
    providerBalance: 'کیف پول و موجودی ارائه‌دهنده‌ها',
    allTags: 'همه تگ‌ها',
    hourlyBilling: 'تمدید بر اساس مصرف ساعتی پنل',
    monthlyBilling: 'تمدید بر اساس دوره زمانی مشخص',
    lastRenewalDate: 'تاریخ شروع یا آخرین تسویه مالی سرور',
    addTagBtn: 'ساخت تگ جدید',
    addProviderBtn: 'ثبت ارائه‌دهنده',
    pingerSim: 'ارسال بسته به سمت میزبان مانیتورینگ...',
    pingerOffline: 'میزبان پاسخ نمی‌دهد! (پورت مسدود یا سرور خاموش است)',
    pingerOnline: 'پاسخ دریافت شد از آی‌پی {ip}: زمان={ms} میلی‌ثانیه',
    sshCmdCopy: 'کپی دستور اتصال فوری SSH برای پاورشل / خط فرمان:',
    pingCmdCopy: 'کپی دستور پینگ مستمر در Command Prompt ویندوز:',
    pinPrompt: 'رمز عبور ۴ رقمی خود را وارد کنید:',
    createPinPrompt: 'یک رمز عبور ۴ رقمی تعیین کنید:',
    confirmPinLock: 'فعال‌سازی رمز عبور',
    disableLock: 'غیرفعال‌سازی رمز عبور برنامه',
    hourlyBalanceExhaust: 'موجودی اعتبار این ارائه‌دهنده به زودی تمام خواهد شد!',
    quickCreds: 'نمایش سریع کلمه‌های عبور و رمزهای نودها',
    unassigned: 'دسته‌بندی نشده',
    daysLeftText: '{days} روز باقی‌مانده از دوره',
    expiredText: 'دوره منقضی شده ({days} روز پیش)',
    todayRenew: 'امروز سررسید پرداخت فاکتور تمدید است!',
    sysadminLog: 'دفترچه رویدادها',
    viewAllLogs: 'مشاهده کل رویدادها',
    addLogsTitle: 'رویداد تمدید حیات',
    deletePermConfirm: 'آیا مایل به حذف کامل اطلاعات این سرور هستید؟ این عمل غیرقابل بازگشت است.',
    untrashConfirm: 'بازگردانی مجدد سرور به لیست سرورهای فعال؟',
    statsLevel: 'سطح شما: {level}',
    statsTitleText: 'لقب کسب شده: {title}',
    gamificationSubTitle: 'جدول دستاوردها و وظایف',
    personalNotesPlaceholder: 'یادداشت‌های فنی یا کدهای داکر کامپوز، کلیدهای SSH، مشخصات کلاینت‌ها و پورت‌های اختصاصی...',
    optional: 'اختیاری',
    searchCategory: 'فیلتر بر اساس دسته‌بندی',
    resetApp: 'ریست کامل برنامه',
    resetAppDesc: 'این دستور تمام سرورهای ثبت شده، شناسنامه‌ها، برچسب‌ها، پین امنیتی و تنظیمات موجود را به صورت دائمی حذف و برنامه را به حالت اولیه باز می‌گرداند.',
    resetAppConfirm: 'هشدار جدی: این عمل کل پایگاه داده محلی شامل تمام سرورها، تگ‌ها، نام‌های کاربری، رمزهای عبور و تاریخچه تمدیدها را به طور دائم منحدم می‌کند و ابداً قابل بازگردانی نیست. آیا مایل به ریست کامل برنامه هستید؟',
    resetAppBtn: 'حذف کامل تمام اطلاعات و ریست برنامه',
    showTrashServers: 'سرورهای حذف شده (سطل زباله)',
  }
};
